src/controllers/CallUMAPal.py
import binascii
import pickle
import os
from flask import render_template, session, Blueprint, request
import base64
from ..models.CartModel import CartModel

callumapal = Blueprint('CallUMAPal', __name__)

CartModel = CartModel()


@callumapal.route('/umapal/callumapal', methods=['POST'])
def index():
    email = session.get('email')
    user_cart = CartModel.select_items_from_cart(email)
    user_cart = base64.b64encode(pickle.dumps(user_cart))
    actual_request = binascii.hexlify(os.urandom(16)).decode('utf-8')

    return render_template('callumapal.html', form=request.form, user_cart=str(user_cart, 'utf-8'), actual_request=actual_request)

src/controllers/GetPoster.py
from flask import render_template, Blueprint

from ..models.PhotosModel import *

getposter = Blueprint('GetPoster', __name__)

PhotosModel = PhotosModel()

@getposter.route('/getposter')
@getposter.route('/getposter/<region>')
def index(region='Africa'):
    photos = PhotosModel.select_photos_by_continent(region)

    return render_template('navbar.html') + render_template('getposter.html', region=region, photos=photos)

src/controllers/Home.py
from flask import render_template, session, Blueprint

home = Blueprint('Home', __name__)


@home.route('/')
@home.route('/home')
def index():
    return render_template('navbar.html') + render_template('home.html')

src/controllers/MyAccount.py
from flask import render_template, session, Blueprint, request, redirect
from ..models.UsersModel import UsersModel

myaccount = Blueprint('MyAccount', __name__)

UsersModel = UsersModel()


@myaccount.route('/myaccount')
def index():
    return render_template('navbar.html') + render_template('myaccount.html')


@myaccount.route('/myaccount/add_new_user', methods=['POST', 'GET'])
def add_new_user():
    if not email_used(request.form['email']):
        UsersModel.insert_new_user(request.form['fname'], request.form['lname'], request.form['email'], request.form['password'])
        session['login'] = request.form['fname']
        session['email'] = request.form['email']
        return redirect('/home')
    else:
        emailused = True
        return render_template('navbar.html') + render_template('myaccount.html', email_used=emailused)


def email_used(email):
    user = UsersModel.select_user_by_email(request.form['email'])
    if len(user) > 0:
        return True
    return False

src/controllers/MyCart.py
from flask import render_template, session, url_for, Blueprint, redirect, request
from ..models.CartModel import CartModel

mycart = Blueprint('MyCart', __name__)

CartModel = CartModel()


@mycart.route('/mycart')
def index():
    if 'email' in session:
        user_cart = CartModel.select_items_from_cart(session['email'])
        cart_total_price = get_cart_total_price(user_cart)
        return render_template('navbar.html') + render_template('mycart.html', user_cart=user_cart, cart_total_price=cart_total_price)
    else:
        return redirect(url_for('MyAccount.index'))


def get_cart_total_price(user_cart):
    cart_price = 0
    for i in range(len(user_cart)):
        cart_price += user_cart[i]['price']
    return cart_price


@mycart.route('/mycart/add_to_cart/<id>', methods=['POST'])
def add_to_cart(id):
    if 'email' in session:
        price = 100000
        if request.form['radio_buttons'] == '40x50':
            price = 29.99
        elif request.form['radio_buttons'] == '50x70':
            price = 39.99
        elif request.form['radio_buttons'] == '60x90':
            price = 59.99
        elif request.form['radio_buttons'] == '100x150':
            price = 79.99
        elif request.form['radio_buttons'] == '120x180':
            price = 99.99

        price = price * int(request.form['quantity'])
        CartModel.insert_item_into_cart(session['email'], id, request.form['quantity'], request.form['radio_buttons'], price)
        return redirect(url_for('MyCart.index'))
    else:
        return redirect(url_for('MyAccount.index'))


@mycart.route('/mycart/remove_item/<poster_id>/<quantity>/<size>')
def remove_item(poster_id, quantity, size):
    CartModel.delete_item(session['email'], poster_id, quantity, size)
    return redirect(url_for('MyCart.index'))


@mycart.route('/mycart/remove_all_items')
def remove_all_items():
    CartModel.delete_all(session['email'])
    return redirect(url_for('MyCart.index'))

src/controllers/MyOrders.py
from flask import render_template, session, url_for, Blueprint, redirect, make_response
from ..models.OrdersModel import OrdersModel

myorders = Blueprint('MyOrders', __name__)

OrderModel = OrdersModel()


@myorders.route('/myorders', methods=['POST', 'GET'])
def index():
    if 'email' in session:
        user_orders_tmp = OrderModel.select_orders(session['email'])
        if len(user_orders_tmp) > 0:
            user_orders = [{'items': [user_orders_tmp[0]]}]
            i = 0
            for j in range(1, len(user_orders_tmp)):
                if user_orders_tmp[j]['order_id'] == user_orders_tmp[j - 1]['order_id']:
                    user_orders[i]['items'].append(user_orders_tmp[j])
                else:
                    user_orders[i]['order_total_price'] = get_order_total_price(user_orders[i]['items'])
                    i += 1
                    user_orders.append({'items': [user_orders_tmp[j]]})

            user_orders[i]['order_total_price'] = get_order_total_price(user_orders[i]['items'])
            return render_template('navbar.html', user_orders=user_orders) + render_template('myorders.html', user_orders=user_orders)
        else:
            return render_template('navbar.html', user_orders=[]) + render_template('myorders.html', user_orders=[])
    else:
        return redirect(url_for('MyAccount.index'))


def get_order_total_price(user_order):
    cart_price = 0
    for i in range(len(user_order)):
        cart_price += user_order[i]['price']
    return cart_price

src/controllers/Navbar.py
from flask import session, Blueprint, request, redirect
from ..models.UsersModel import UsersModel

navbar = Blueprint('Navbar', __name__)

UsersModel = UsersModel()


@navbar.route('/navbar/login', methods=['POST'])
def login():
    email = request.form['email_login']
    password = request.form['password_login']
    user = UsersModel.select_user_by_email_and_password(email, password)

    if user:
        session['login'] = user['first_name']
        session['email'] = user['email']
        session['password'] = True
    else:
        session['password'] = False

    return redirect(request.referrer)


@navbar.route('/navbar/disconnect_user', methods=['GET'])
def disconnect_user():
    session.pop('login', None)
    session.pop('email', None)
    session.pop('password', None)
    return redirect(request.referrer)

src/controllers/PaymentCancel.py
from flask import render_template, session, Blueprint, request

paymentcancel = Blueprint('PaymentCancel', __name__)


@paymentcancel.route('/paymentcancel', methods=['POST'])
def index():
    actual_request = request.form['cartID']

    return render_template('navbar.html') + render_template('paymentcancel.html', actual_request=actual_request)

src/controllers/PaymentForm.py
from flask import render_template, session, url_for, Blueprint, redirect

paymentform = Blueprint('PaymentForm', __name__)


@paymentform.route('/paymentform')
def index():
    if 'email' in session:
        return render_template('navbar.html') + render_template('paymentform.html')
    else:
        return redirect(url_for('MyAccount'))

src/controllers/PaymentSuccess.py
import base64
from flask import render_template, session, Blueprint, request
from ..models.OrdersModel import *
from ..models.CartModel import *
import datetime
import pickle

paymentsuccess = Blueprint('PaymentSuccess', __name__)

CartModel = CartModel()
OrdersModel = OrdersModel()


@paymentsuccess.route('/paymentsuccess', methods=['POST'])
def index():
    actual_request = request.form['cartID']
    user_cart = pickle.loads(base64.b64decode(request.form['user_cart_encoded']))
    date = datetime.datetime.now().strftime("%d %b, %Y")

    for i in range(len(user_cart)):
        OrdersModel.insert_order(session['email'], request.form['cartID'], user_cart[i]['photo_id'], user_cart[i]['price'], user_cart[i]['size'], user_cart[i]['quantity'], date)

    CartModel.delete_all(session['email'])

    return render_template('navbar.html') + render_template('paymentsuccess.html', user_cart=user_cart, actual_request=actual_request)

src/controllers/PosterDescription.py
from flask import render_template, session, Blueprint
from ..models.PhotosModel import PhotosModel

posterdescription = Blueprint('PosterDescription', __name__)

PhotoModel = PhotosModel()

@posterdescription.route('/posterdescription')
@posterdescription.route('/posterdescription/<id>')
def index(id=28):
    photo = PhotoModel.select_photo_by_id(id)

    return render_template('navbar.html') + render_template('posterdescription.html', photo=photo)

src/templates/callumapal.html
<html>
    <head>
        <title>Connecting to UMAPal</title>
    </head>
    <body onload="document.umapal.submit()">
        <h3>Connecting to UMAPal...</h3>
        <form name="umapal" action="{{ url_for('umapal.processpayment') }}" method="post">
            <input type="hidden" name="cmd" value="_xclick">
            <input type="hidden" name="business" value="{{ user_cart[0]['email_user'] }}">
            <input type="hidden" name="user_cart" value="{{ user_cart }}">
            <input type="hidden" name="address_override" value="1">
            <input type="hidden" name="first_name" value="{{ form['fname'] }}">
            <input type="hidden" name="last_name" value="{{ form['lname'] }}">
            <input type="hidden" name="address1" value="{{ form['address'] }}">
            <input type="hidden" name="city" value="{{ form['city'] }}">
            <input type="hidden" name="zip" value="{{ form['postal_code'] }}">
            <input type="hidden" name="country" value="{{ form['country'] }}">
            <input type="hidden" name="return" value="{{ url_for('PaymentSuccess.index') }}">
            <input type="hidden" name="cancel_return" value="{{ url_for('PaymentCancel.index') }}">
            <input type="hidden" name="cartID" value="{{ actual_request }}">
            <input type="submit" value="Send to UMAPal" />
        </form>
    </body>
</html>

src/templates/getposter.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ region }}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/getposter.css') }}">
    </head>
    <body>
        {% set modulo = photos|length % 3 %}
        {% if photos|length >= 3 %}
            {% for i in range(0, photos|length // 3) %}
                <div class="flex_container">
                    <a href="{{ url_for('PosterDescription.index', id=photos[3 * i]['id']) }}">
                        <img src="{{ url_for('static', filename=photos[3 * i]['filepath']) }}" alt="">
                    </a>
                    <a href="{{ url_for('PosterDescription.index', id=photos[3 * i + 1]['id']) }}">
                        <img src="{{ url_for('static', filename=photos[3 * i + 1]['filepath']) }}" alt="">
                    </a>
                    <a href="{{ url_for('PosterDescription.index', id=photos[3 * i + 2]['id']) }}">
                        <img src="{{ url_for('static', filename=photos[3 * i + 2]['filepath']) }}" alt="">
                    </a>
                </div>
            {% endfor %}
        {% endif %}
        {% if photos|length % 3 != 0 %}
            <div class="flex_container">
                {% for i in range(photos|length % 3) %}
                    <span1>
                    <a href="{{ url_for('PosterDescription.index', id=photos[photos|length - (photos|length % 3) + i]['id']) }}">
                        <img src="{{ url_for('static', filename=photos[photos|length - (photos|length % 3) + i]['filepath']) }}" alt="">
                    </a>
                    </span1>
                {% endfor %}
            </div>
        {% endif %}
    </body>
</html>

src/templates/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title style="display: none">Home</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
    </head>
    <body>
        <div class="flex_container">
            <h1>Get the poster of your dreams on this website</h1>
            <div class="steps">
                <div class="box">Find the photo you like the most</div>
                <div class="arrow">&#62;</div>
                <div class="box">Select the size of the poster you want</div>
                <div class="arrow">&#62;</div>
                <div class="box">Order it</div>
            </div>
        </div>
    </body>
</html>

src/templates/myaccount.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My account</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/myaccount.css') }}">
    </head>
    <body>
        <script>
    var match_password = function () {
        if (document.getElementById('password').value == document.getElementById('confirm').value) {
            document.getElementById('message').style.color = 'green';
            document.getElementById('message').innerHTML = 'matching';
            document.getElementById('submit').disabled = false;
        } else {
            document.getElementById('message').style.color = 'red';
            document.getElementById('message').innerHTML = 'not matching';
            document.getElementById('submit').disabled = true;
        }
    }

        </script>
        <div class="form_box">
            <form method="post"
                  class="font form"
                  action="{{ url_for('MyAccount.add_new_user') }}">
                <div class="title">Create your account</div>
                <div class="line">
                    <input type="text" id="fname" name="fname" placeholder="First name" pattern="[A-Za-z]+" required>
                    <br>
                    <input type="text" id="lname" name="lname" placeholder="Last name" pattern="[A-Za-z]+" required>
                    <br>
                </div>
                <div class="line">
                    <input type="email" id="email" name="email" placeholder="Email address" pattern="^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$" required>
                    <br>
                    <br>
                </div>
                <div class="line">
                    <input type="password" id="password" name="password" placeholder="Password" onkeyup='match_password();' pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8, 16}" required>
                    <br>
                    <input type="password" id="confirm" name="confirm" placeholder="Confirm password" onkeyup='match_password();' pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8, 16}" required>
                    <br>
                    <span id='message'></span>
                </div>
                <div style="display: flex; flex-direction: column; color: red">
                    <input id="submit" type="submit" value="Submit">
                    {% if email_used %}Email used by another user{% endif %}
                </div>
            </form>
        </div>
    </body>
</html>

src/templates/mycart.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My cart</title>
        <link rel="stylesheet"
              type="text/css"
              href="{{ url_for('static', filename='css/mycart.css') }}">
    </head>
    <body>
        {% for item in user_cart %}
            <div class="flex_container font">
                <div style="display: flex;
                            flex-direction: row;
                            margin-bottom: 1px;
                            background-color: #f8f8f8">
                    <a href="{{ url_for('PosterDescription.index', id=item['id']) }}">
                        <img src="{{ url_for('static', filename=item['filepath']) }}" alt="">
                    </a>
                    <div class="infos">
                        <p style="">
                            {{ item['continent'] }} #{{ item['id'] }}
                            <br>
                        </p>
                        <p style="">
                            Quantity: {{ item['quantity'] }}
                            <br>
                        </p>
                        <p style="">
                            Size (cm): {{ item['size'] }}}
                            <br>
                        </p>
                        <p style="">
                            Price: {{ item['price'] }}$
                            <br>
                        </p>
                    </div>
                    <div style="flex-grow: 1">
                        <a href="{{ url_for('MyCart.remove_item', poster_id=item['id'], quantity=item['quantity'], size=item['size']) }}"
                           style="font-size: small;
                                  float: right">Remove from cart</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <p class="font">Total price: {{ cart_total_price }}$</p>
        <a href="{{ url_for('PaymentForm.index') }}">
            <button>Pay</button>
        </a>
    </body>
</html>

src/templates/myorders.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My orders</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/myorders.css') }}">
    </head>
    <body>
        <h1 class="font" style="margin: 30px">My orders</h1>
        {% for order in user_orders %}
            <h2 style="color: #404040;
                       display: flex;
                       flex-direction: column"
                class="font">{{ order['items'][0]['date'] }} --> order #{{ order['items'][0]['order_id'] }}</h2>
            {% for item in order['items'] %}
                <div class="flex_container font">
                    <a href="{{ url_for('PosterDescription.index', id=item['photo_id']) }}">
                        <img src="{{ url_for('static', filename=item['filepath']) }}" alt="">
                    </a>
                    <div class="infos">
                        <p style="">
                            {{ item['continent'] }} #{{ item['id'] }}
                            <br>
                        </p>
                        <p style="">
                            Quantity: {{ item['quantity'] }}
                            <br>
                        </p>
                        <p style="">
                            Size (cm): {{ item['size'] }}
                            <br>
                        </p>
                        <p style="">
                            Price: {{ item['price'] }}$
                            <br>
                        </p>
                    </div>
                </div>
            {% endfor %}
            <p class="font total_price">Total price: {{ order['order_total_price'] }}$</p>
        {% endfor %}
    </body>
</html>

src/templates/navbar.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" lang="en">
    <head>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/navbar.css') }}">
        <meta charset="UTF-8">
    </head>
    <body>
        <div class="navbar">
            <a class="navbar_button" href="{{ url_for('Home.index') }}"><span>Home</span></a>
            <a class="navbar_button" href="{{ url_for('GetPoster.index', region='Europe') }}"><span>Europe</span></a>
            <a class="navbar_button" href="{{ url_for('GetPoster.index', region='Asia') }}"><span>Asia</span></a>
            <a class="navbar_button" href="{{ url_for('GetPoster.index', region='America') }}"><span>America</span></a>
            <a class="navbar_button" href="{{ url_for('GetPoster.index', region='Africa') }}"><span>Africa</span></a>
            <a class="navbar_button" href="{{ url_for('GetPoster.index', region='Oceania') }}"><span>Oceania</span></a>
            <a class="navbar_button" href="{{ url_for('MyCart.index') }}"><span>My cart</span></a>
            {% if not session['login'] %}
                <div class="navbar_button showhim nav_right">
                    My account
                    <form class="showme" method="post" action="{{ url_for('Navbar.login') }}">
                        <input type="email" id="email_login" name="email_login" placeholder="Email" required>
                        <input type="password" id="password_login" name="password_login" placeholder="Password" required>
                        <input type="submit" style="width: 100%" value="Submit">
                        <div style="color:red">
                            {% if not session['password'] %}
                                Wrong email or password
                            {% endif %}
                            <a href="{{ url_for('MyAccount.index') }}" style="font-size: small">No Account ?</a>
                        </div>
                    </form>
                </div>
            {% else %}
                <div class="navbar_button showhim nav_right">
                    {{ session['login'] }}
                    <div class="showme">
                        <a href="{{ url_for('MyOrders.index') }}">
                            <button>My orders</button>
                        </a>
                        <a href="{{ url_for('Navbar.disconnect_user') }}">
                            <button>Log out</button>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </body>
</html>

src/templates/paymentcancel.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <h1>Payment canceled</h1>
        Operation code: {{ actual_request }}
    </body>
</html>

src/templates/paymentform.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" , lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Payment</title>
        <link rel="stylesheet"
              type="text/css"
              href="{{ url_for('static', filename='css/paymentform.css') }}">
    </head>
    <body>
        <div class="form_box">
            <form method="post" class="font" action="{{ url_for('CallUMAPal.index') }}">
                <div class="font" style="text-align: center; font-size: 20px">Add your shipment address</div>
                <div class="line">
                    <input type="text" id="fname" name="fname" placeholder="First name" pattern="[A-Za-z]+" required>
                    <br>
                    <input type="text" id="lname" name="lname" placeholder="Last name" pattern="[A-Za-z]+" required>
                    <br>
                </div>
                <div class="column">
                    <input style="width: 95%" type="text" name="address" placeholder="Address" required>
                    <input style="width: 95%" type="text" name="appartment" placeholder="Appartment" required>
                </div>
                <div class="line">
                    <input type="number" name="postal_code" placeholder="Postal code" required>
                    <input type="text" name="city" placeholder="City" required>
                    <input type="text" name="country" placeholder="Country" required>
                </div>
                <div style="text-align: center">
                    <input id="submit" type="submit" value="Submit">
                </div>
            </form>
        </div>
    </body>
</html>

src/templates/paymentsuccess.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <h1>Payment completed</h1>
        Operation code: {{ actual_request }}
        {% set url = url_for('MyOrders.index') %}
        {% set refresh = 3 %}
        {% set header = 'refresh:' ~ refresh ~ '; url=' ~ url %}
        {% set js = 'window.setTimeout(function() { window.location.href = "' ~ url ~ '"; }, ' ~ refresh*1000 ~ ');' %}
        <meta http-equiv="refresh" content="{{ refresh }}; url={{ url }}">
        <script>{{ js }}</script>
    </body>
</html>

src/templates/posterdescription.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ photo['continent'] }} #{{ photo['id'] }}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/posterdescription.css') }}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script>
        display_price = function () {
            let size = $("input:radio[name ='radio_buttons']:checked").val();
            let price = 0;

            switch (size) {
                case "40x50":
                    price = 29.99;
                    break;
                case "50x70":
                    price = 39.99;
                    break;
                case "60x90":
                    price = 59.99;
                    break;
                case "100x150":
                    price = 79.99;
                    break;
                case "120x180":
                    price = 99.99;
                    break;
            }

            if (price !== 0) {
                document.getElementById('price').innerHTML = (parseInt(document.getElementById('quantity').value) * price).toFixed(2) + '$';
            }
        }
        </script>
    </head>
    <body>
        <div class="flex_container">
            <div class="photo_div">
                <img src="{{ url_for('static', filename=photo['filepath']) }}" alt="">
            </div>
            <div class="product_info">
                <form class="size_form" name="size_form" action="{{ url_for('MyCart.add_to_cart', id=photo['id']) }}" method="post">
                    <div class="font title">{{ photo['continent'] }} #{{ photo['id'] }}</div>
                    <label class="font">Size (cm):</label>
                    <div class="size_container">
                        <label for="size1">40 x 50</label>
                        <input id="size1" class="btn btn-default" type="radio" value="40x50" name="radio_buttons" onclick="display_price();" required>
                        <label for="size2">50 x 70</label>
                        <input id="size2" class="btn btn-default" type="radio" value="50x70" name="radio_buttons" onclick="display_price();">
                        <label for="size3">60 x 90</label>
                        <input id="size3" class="btn btn-default" type="radio" value="60x90" name="radio_buttons" onclick="display_price();">
                        <label for="size4">100 x 150</label>
                        <input id="size4" class="btn btn-default" type="radio" value="100x150" name="radio_buttons" onclick="display_price();">
                        <label for="size5">120 x 180</label>
                        <input id="size5" class="btn btn-default" type="radio" value="120x180" name="radio_buttons" onclick="display_price();">
                    </div>
                    <label for="quantity" class="font">Quantity:</label>
                    <select id="quantity" onchange="display_price();" name="quantity">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                    <br>
                    <br>
                    <div style="text-align: center" class="buy">
                        <button type="submit" style="font-size: 16px">Add to cart</button>
                        <div id="price" class="font"></div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>